### ISSUE TITLE
Windows: cairosvg library requires installing GTK runtime

### ISSUE THREAD

**Issue by endorxmr** [mj-xmr/SolOptXMR#119]
```
$ ./soloptxmr.py
Traceback (most recent call last):
  File "C:\Users\endor\Projects\SolOptXMR\soloptxmr.py", line 25, in <module>
    from src import generator
  File "C:\Users\endor\Projects\SolOptXMR\src\generator.py", line 23, in <module>
    from . import weather_lib
  File "C:\Users\endor\Projects\SolOptXMR\src\weather_lib.py", line 24, in <module>
    from cairosvg import svg2png
  File "C:\Users\endor\Projects\SolOptXMR\.venv-ui\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\endor\Projects\SolOptXMR\.venv-ui\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\endor\Projects\SolOptXMR\.venv-ui\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\endor\Projects\SolOptXMR\.venv-ui\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\Program Files (x86)\GtkSharp\2.12\bin\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1
```

Found [this reply](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/issues/8#issuecomment-1059071881) which suggests installing [this GTK runtime for windows](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer). That solves the issue.

**Comment by mj-xmr** [comment]
Cool. That's very useful.
